Lab2 done
LucarisVey/OOP pull request #4
Opened 2023-03-07 20:46 UTC by LucarisVey

2023-03-09 10:54 UTC, RuslanSlobodian requested changes

2023-03-09 10:54 UTC, RuslanSlobodian commented on lab2/src/Text.java
> +            textAfterProcessing += (someText[i] + " ");
В циклах краще використовувати клас StringBuilder

2023-03-09 10:54 UTC, RuslanSlobodian commented on lab2/src/Text.java
> +    private String character;
Якщо це один символ, тоді може бути тип char

2023-03-09 10:54 UTC, RuslanSlobodian commented on lab2/src/Text.java
> +                String newText = someText[i].replace(character, "");
пустий char можна передати як '\0'

2023-03-09 10:54 UTC, RuslanSlobodian commented on lab2/src/Text.java
> +                String newText = someText[i].replace(character, "");
String newText лишній об'єкт, можна відразу присвоювати в той самий елемент масиву
someText[i] = someText[i].replace(character, '\0');

2023-03-12 16:17 UTC, LucarisVey commented
При використані в replace '\0', замість замінюваних символів появляються маленькі null.

2023-03-13 09:29 UTC, RuslanSlobodian requested changes

2023-03-13 09:29 UTC, RuslanSlobodian commented on lab2/src/Text.java
> +                    throw new NullPointerException();
NullPointerException викидається тоді, коли викликаєш в обєкта методі, а він на цей момент ще не ініціалізований, тобто null.
а тут інше, просто тексту не було у файлі

2023-03-13 19:35 UTC, doliinyk commented on lab2/src/Text.java
> +                String newText = someText[i].replace(character, "");
> 

а можна як ''

2023-03-15 19:28 UTC, RuslanSlobodian approved these changes

2023-03-15 19:29 UTC, merged